# Copyright (c) 2022, Itential, LLC
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)

- name: Validate distribution major version
  ansible.builtin.fail:
    msg: Download not supported for version 7
  when: ansible_distribution_major_version == "7"

- name: Validate offline_install variable
  ansible.builtin.fail:
    msg: offline_install must be set to false for download
  when:
    - offline_install is defined
    - offline_install

- name: Include release vars
  ansible.builtin.include_vars:
    file: "{{ item }}"
  with_first_found:
    - "release-{{ iap_release }}.yaml"
    - "release-undefined.yaml"

- name: Check for valid Redis release
  ansible.builtin.fail:
    msg: "missing or invalid redis_packages"
  when: redis_packages == "UNDEFINED"

- name: Install epel-release yum repo
  ansible.builtin.yum:
    name: "{{ epel_location }}"
    state: present
    update_cache: true
    disable_gpg_check: true

- name: Install Remi repo
  ansible.builtin.yum:
    name: "{{ redis_repo_url[ansible_distribution_major_version] }}"
    state: present
    disable_gpg_check: true

- name: Download Redis rpms
  ansible.builtin.import_role:
    name: offline
    tasks_from: download-rpms
  vars:
    download_method: yum_module
    download_packages: "{{ redis_packages[ansible_distribution_major_version] }}"
    download_dir: "{{ redis_rpms_download_dir_target_node }}"

- name: Copy rpms to control node
  ansible.builtin.import_role:
    name: offline
    tasks_from: fetch-packages
  vars:
    src_dir: "{{ redis_rpms_download_dir_target_node }}"
    dest_dir: "{{ redis_rpms_download_dir_control_node }}"
