# Copyright (c) 2024, Itential, Inc
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)
---
platform_packages:
  - bzip2-devel
  - gcc
  - glibc-common
  - libffi-devel
  - openldap
  - openldap-clients
  - openssl-devel
  - zlib-devel

iap_nodejs_package: "@nodejs:18"

python_version: 3.9
python_executable: "/usr/bin/python{{ python_version }}"
pip_executable: "/usr/bin/pip{{ python_version }}"

python_packages:
  - python3
  - python3-pip

base_python_dependencies:
  - pip
  - setuptools
  - wheel

app_python_dependencies:
  - textfsm==1.1.2
  - jinja2==2.11.3
  - markupsafe==2.0.1
  - pymongo

mongodb_version: 6.0

mongodb_tools_packages:
  - mongodb-database-tools
  - mongodb-mongosh

mongo_shell: mongosh
