# Copyright (c) 2022, Itential, LLC
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)

## VAULT
- name: Install Vault
  hosts: vault
  become: true

  roles:
    # Pull in the common vars
    - role: common_vars

  tasks:
    - name: Install and initialize Vault
      ansible.builtin.import_role:
        name: vault
        tasks_from: main
      tags:
        - vault
        - vault_install

    - name: Vault (initialize server and unseal)
      ansible.builtin.import_role:
        name: vault
        tasks_from: unseal
      tags:
        - vault
        - vault_unseal
