# Copyright (c) 2022, Itential, LLC
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)

- name: Download Gateway Python rpms
  ansible.builtin.import_role:
    name: offline
    tasks_from: download-rpms
  vars:
    download_method: yum_module
    download_packages: "{{ gateway_python_packages }}"
    download_dir: "{{ iag_rpms_download_dir_target_node }}"
  tags: download_gateway_python_packages

- name: Include tasks to install Python on version 8
  ansible.builtin.include_tasks:
    file: "python-for-8.yaml"
  when: ansible_distribution_major_version == "8"

- name: Include tasks to install Python on version 9
  ansible.builtin.include_tasks:
    file: "python-for-9.yaml"
  when: ansible_distribution_major_version == "9"

- name: Download Python wheels
  ansible.builtin.import_role:
    name: offline
    tasks_from: download-wheels
  vars:
    wheel_files: "{{ iag_python_dependencies }}"
    download_dir: "{{ iag_wheels_download_dir_target_node }}"

- name: Include tasks to create IAG archive
  ansible.builtin.include_tasks:
    file: create-iag-archive.yml

- name: Uninstall Python rpms
  ansible.builtin.yum:
    name: "{{ item }}"
    state: absent
    autoremove: true
  with_items: "{{ python_install_result.results | selectattr('changed', 'equalto', true) | map(attribute='item') }}"
