# Copyright (c) 2024, Itential, Inc
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)
---
- name: Install Python
  ansible.builtin.include_role:
    name: python
  tags: install_python

- name: Setup python virtual environment
  ansible.builtin.command:
    chdir: "{{ iag_install_dir }}"
    cmd: "{{ python_executable }} -m venv venv"
  changed_when: true

- name: Include the virtual environment in default shell
  ansible.builtin.shell:
    cmd: echo source {{ iag_install_dir }}/venv/bin/activate > /etc/profile.d/venv.sh
  changed_when: true

- name: Install Python dependencies
  ansible.builtin.include_role:
    name: python
    tasks_from: install-dependencies
  tags: install_python
