# Copyright (c) 2022, Itential, LLC
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)

- name: Include release vars
  ansible.builtin.include_vars:
    file: "{{ item }}"
  with_first_found:
    - "{{ iag_release }}-{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version }}.yaml"
    - "release-undefined.yaml"

- name: Check for valid IAG release
  ansible.builtin.fail:
    msg: "missing or invalid iag_release"
  when: iag_release == "UNDEFINED"

- name: Include base OS updates
  ansible.builtin.include_role:
    name: os
  tags: base_os_updates

- name: Create temporary working directory
  ansible.builtin.tempfile:
    state: directory
  register: workingdir

- name: Install Gateway packages (online)
  ansible.builtin.yum:
    name: "{{ item }}"
    state: present
  with_items: "{{ gateway_packages }}"
  when: not offline_install
  tags: install_gateway_packages

- name: Install Gateway packages (offline)
  ansible.builtin.import_role:
    name: offline
    tasks_from: install-rpms
  vars:
    rpms_path: "{{ iag_rpms_path }}"
  when: offline_install
  tags: install_gateway_packages

- name: Write IAG release file
  ansible.builtin.lineinfile:
    path: "{{ itential_release_file }}"
    line: "GATEWAY={{ iag_release }}"
    create: true
  changed_when: true

- name: Create itential group
  ansible.builtin.group:
    name: "{{ iag_group }}"

- name: Create itential user
  ansible.builtin.user:
    name: "{{ iag_user }}"
    group: "{{ iag_group }}"
    groups: wheel
    generate_ssh_key: true
    state: present

- name: Create working directories
  ansible.builtin.file:
    name: "{{ item }}"
    owner: "{{ iag_user }}"
    group: "{{ iag_group }}"
    mode: "0775"
    state: directory
  with_items:
    - /etc/ansible
    - "{{ iag_log_dir }}"
    - "{{ iag_install_dir }}"
    - "{{ iag_properties_dir }}"
    - "{{ iag_data_dir }}"
    - "{{ iag_data_dir }}/data"
    - "{{ iag_resources_dir }}"
    - "{{ iag_resources_dir }}/ansible/collections"
    - "{{ iag_resources_dir }}/ansible/inventory"
    - "{{ iag_resources_dir }}/ansible/modules"
    - "{{ iag_resources_dir }}/ansible/roles"
    - "{{ iag_resources_dir }}/ansible/collections"
    - "{{ iag_resources_dir }}/ansible/playbooks"
    - "{{ iag_resources_dir }}/ansible/plugins/modules"
    - "{{ iag_resources_dir }}/ansible/scripts"
    - "{{ iag_properties_dir }}/certs"
    - "{{ iag_resources_dir }}/nornir/conf"
    - "{{ iag_resources_dir }}/nornir/inventory"
    - "{{ iag_resources_dir }}/nornir/modules"
    - "{{ iag_resources_dir }}/scripts"
    - "{{ iag_resources_dir }}/terraform/scripts"
    - "{{ iag_resources_dir }}/python-venvs"

- name: Copy certs
  ansible.builtin.include_tasks:
    file: copy-certs.yml
  when: iag_https and iag_ssl_copy_certs

- name: Check if Python is already installed
  ansible.builtin.stat:
    path: "/usr/local/bin/python3"
  register: python_installed

- name: Check if Pip is already installed
  ansible.builtin.stat:
    path: "/usr/local/bin/pip3"
  register: pip_installed

# Installing python3 on RHEL7 & Centos7 requires building python from source
# in order to support the documented version of python3. Dynamically include a
# task file that can handle the steps to build from source when we detect that
# this host is a version 7.
- name: Include tasks to install python on version 7 (online)
  ansible.builtin.include_tasks:
    file: "python-for-7.yaml"
  when:
    - ansible_distribution_major_version == "7"
    - not python_installed.stat.exists or not pip_installed.stat.exists
    - not offline_install

# Include a file for RHEL8 steps to install the appropriate version of python.
- name: Include tasks to install python on version 8 (online)
  ansible.builtin.include_tasks:
    file: "python-for-8.yaml"
  when:
    - ansible_distribution_major_version == "8"
    - not python_installed.stat.exists or not pip_installed.stat.exists
    - not offline_install

- name: Include tasks to install python on version 8 (offline)
  ansible.builtin.include_tasks:
    file: "python-for-8-offline.yml"
  when:
    - ansible_distribution_major_version == "8"
    - offline_install

# Include a file for RHEL9 steps to install the appropriate version of python.
- name: Include tasks to install python on version 9 (online)
  ansible.builtin.include_tasks:
    file: "python-for-9.yaml"
  when:
    - ansible_distribution_major_version == "9"
    - not python_installed.stat.exists or not pip_installed.stat.exists
    - not offline_install

- name: Include tasks to install python on version 9 (offline)
  ansible.builtin.include_tasks:
    file: "python-for-9-offline.yml"
  when:
    - ansible_distribution_major_version == "9"
    - offline_install

- name: Setup python virtual environment
  ansible.builtin.command:
    chdir: "{{ iag_install_dir }}"
    cmd: /usr/local/bin/python3 -m venv {{ iag_venv_name }}

- name: Activate the virtual environment for the current session
  ansible.builtin.shell:
    cmd: "source {{ iag_venv_dir }}/bin/activate"
  changed_when: true

- name: Include the virtual environment in default shell
  ansible.builtin.shell:
    cmd: echo source {{ iag_venv_dir }}/bin/activate > /etc/profile.d/venv.sh
  changed_when: true

- name: Install Python dependencies (online)
  ansible.builtin.pip:
    name: "{{ item }}"
    virtualenv: "{{ iag_venv_dir }}"
  with_items: "{{ iag_python_dependencies }}"
  when: not offline_install
  tags: install_python_dependencies

- name: Install Python dependencies (offline)
  when: offline_install
  block:
    - name: Install Python dependencies (offline)
      ansible.builtin.include_role:
        name: offline
        tasks_from: install-wheels
      vars:
        wheels_path: "{{ iag_wheels_download_dir_control_node }}"
        virtual_env: "{{ iag_install_dir }}/venv"
      tags: install_python_dependencies

    - name: Install Python dependencies from IAG requirements file (offline)
      ansible.builtin.include_role:
        name: offline
        tasks_from: install-wheels-archives
      vars:
        wheels_path: "{{ iag_pkgs_path }}"
        virtual_env: "{{ iag_install_dir }}/venv"

# Need to install ansible within the virtual environment
- name: Install Ansible
  when: iag_enable_ansible | bool
  block:
    - name: Install Ansible into the python virtual environment
      ansible.builtin.pip:
        name: "{{ iag_ansible_version }}"
        virtualenv: "{{ iag_venv_dir }}"
      when: not offline_install

    - name: Create Ansible config file
      ansible.builtin.template:
        src: ansible.cfg.j2
        dest: /etc/ansible/ansible.cfg
        backup: true

    - name: Create empty ansible inventory files
      ansible.builtin.file:
        name: "{{ iag_resources_dir }}/ansible/inventory/hosts"
        owner: "{{ iag_user }}"
        group: "{{ iag_group }}"
        mode: "0660"
        state: touch

    - name: Create empty ansible vault file
      ansible.builtin.file:
        name: "{{ iag_install_dir }}/conf/.vault_password_file"
        owner: "{{ iag_user }}"
        group: "{{ iag_group }}"
        mode: "0400"
        state: touch

    - name: Update release file
      ansible.builtin.lineinfile:
        path: "{{ itential_release_file }}"
        line: "ANSIBLE={{ iag_ansible_version }}"
        create: true
      changed_when: true

- name: Install Terraform
  when: iag_enable_terraform | bool
  block:
    - name: Download Terraform
      ansible.builtin.get_url:
        url: "{{ iag_terraform_url }}"
        dest: "{{ workingdir.path }}/{{ iag_terraform_url | basename }}"
        mode: "0644"
      when: not offline_install

    - name: Extract Terraform
      ansible.builtin.unarchive:
        src: "{{ workingdir.path }}/{{ iag_terraform_url | basename }}"
        dest: /usr/local/bin
        remote_src: true
      when: not offline_install

    - name: Install Terraform (offline)
      ansible.builtin.include_tasks:
        file: terraform-offline.yml
      when: offline_install

    - name: Update release file
      ansible.builtin.lineinfile:
        path: "{{ itential_release_file }}"
        line: "TERRAFORM=true"
        create: true
      changed_when: true

- name: Check if Automation Gateway is already installed
  ansible.builtin.stat:
    path: "{{ iag_venv_dir }}/automation-gateway"
  register: iag_installed

- name: Install Automation Gateway
  when: not iag_installed.stat.exists
  block:
    - name: Copy IAG to host
      ansible.builtin.copy:
        src: "{{ iag_whl_file }}"
        dest: "{{ workingdir.path }}/{{ iag_whl_file | basename }}"
        mode: '0644'

    - name: Install IAG
      ansible.builtin.pip:
        name: "{{ workingdir.path }}/{{ iag_whl_file | basename }}"
        virtualenv: "{{ iag_venv_dir }}"

- name: Set ownership/permissions and create properties.yaml
  when: not iag_installed.stat.exists
  block:
    # Using chown and chmod is a faster way to enforce the file ownership and
    # permissions. The file module in ansible checks each and every file/dir
    # in the tree, 'chown -R ' does not, it just sets it.
    - name: Set appropriate ownership on all gateway files
      ansible.builtin.command:
        cmd: "chown -R {{ iag_user }}:{{ iag_group }} {{ iag_venv_dir }}"
      changed_when: true

    - name: Set appropriate permissions on all gateway files
      ansible.builtin.command:
        cmd: "chmod -R 775 {{ iag_venv_dir }}"
      changed_when: true

    - name: Create properties.yaml using template based on the version
      ansible.builtin.template:
        src: "properties.{{ iag_release }}.yaml.j2"
        dest: "{{ iag_properties_dir }}/properties.yaml"
        owner: "{{ iag_user }}"
        group: "{{ iag_group }}"
        mode: "0660"

    - name: Capture python version
      ansible.builtin.command:
        cmd: /usr/local/bin/python3 -V
      register: python_installed_version

    - name: Add a virtual environment for the default python version
      ansible.builtin.command:
        chdir: "{{ iag_resources_dir }}/python-venvs"
        cmd: /usr/local/bin/python3 -m venv {{ python_installed_version.stdout|replace(" ", "-") }}

- name: Create Nornir files
  when: iag_enable_nornir | bool
  block:
    - name: Create Nornir inventory files (empty)
      ansible.builtin.file:
        name: "{{ item }}"
        owner: "{{ iag_user }}"
        group: "{{ iag_group }}"
        mode: "0660"
        state: touch
      with_items:
        - "{{ iag_resources_dir }}/nornir/inventory/defaults.yaml"
        - "{{ iag_resources_dir }}/nornir/inventory/groups.yaml"
        - "{{ iag_resources_dir }}/nornir/inventory/hosts.yaml"

    - name: Create Nornir config file
      ansible.builtin.template:
        src: nornir.config.yaml.j2
        dest: "{{ iag_resources_dir }}/nornir/conf/config.yaml"
        owner: "{{ iag_user }}"
        group: "{{ iag_group }}"
        mode: "0660"

    - name: Update release file
      ansible.builtin.lineinfile:
        path: "{{ itential_release_file }}"
        line: "NORNIR=true"
        create: true
      changed_when: true

- name: Write automation-gateway.service to host
  ansible.builtin.template:
    src: automation-gateway.service.j2
    dest: /etc/systemd/system/automation-gateway.service
    backup: true

# Check if firewalld is running, if it is then open the appropriate ports
- name: Gather service facts
  ansible.builtin.service_facts:

- name: Configure HTTP Port on FirewallD Public Zone
  ansible.posix.firewalld:
    port: "{{ iag_port }}/tcp"
    permanent: true
    state: "{{ iag_https or iag_haproxy | ternary('disabled', 'enabled') }}"
    zone: public
    immediate: true
  when:
    - ansible_facts.services["firewalld.service"] is defined
    - ansible_facts.services["firewalld.service"].state == "running"
    - ansible_facts.services["firewalld.service"].status == "enabled"

- name: Configure HTTPS Port on FirewallD Public Zone
  ansible.posix.firewalld:
    port: "{{ iag_https_port }}/tcp"
    permanent: true
    state: "{{ iag_https or iag_haproxy | ternary('enabled', 'disabled') }}"
    zone: public
    immediate: true
  when:
    - ansible_facts.services["firewalld.service"] is defined
    - ansible_facts.services["firewalld.service"].state == "running"
    - ansible_facts.services["firewalld.service"].status == "enabled"

- name: Allow IAG to listen on tcp port {{ iag_port }}
  community.general.seport:
    ports: "{{ iag_port }}"
    proto: tcp
    setype: http_port_t
    state: present

- name: Start Automation Gateway service
  ansible.builtin.service:
    name: automation-gateway
    enabled: true
    state: restarted
    daemon_reload: true

- name: Update release file
  ansible.builtin.include_tasks:
    file: update-release-file.yaml

- name: Remove temporary working directory
  ansible.builtin.file:
    path: "{{ workingdir.path }}"
    state: absent
