# Copyright (c) 2022, Itential, LLC
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)

- name: Create temporary working directory
  ansible.builtin.tempfile:
    state: directory
  become_user: "{{ python_venv_user }}"
  register: workingdir

- name: Copy IAG to host
  ansible.builtin.copy:
    src: "{{ iag_whl_file }}"
    dest: "{{ workingdir.path }}/{{ iag_whl_file | basename }}"
    mode: '0644'

- name: Upgrade IAG
  ansible.builtin.pip:
    name: "{{ workingdir.path }}/{{ iag_whl_file | basename }}"
    virtualenv: "{{ python_venv }}"
  become_user: "{{ python_venv_user }}"

- name: Restart Automation Gateway service
  ansible.builtin.service:
    name: automation-gateway
    enabled: true
    state: restarted

- name: Remove temporary working directory
  ansible.builtin.file:
    path: "{{ workingdir.path }}"
    state: absent
