# Copyright (c) 2022, Itential, LLC
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)

- name: Download Python rpms
  ansible.builtin.import_role:
    name: offline
    tasks_from: download-rpms
  vars:
    download_method: yum_module
    download_packages: "{{ mongodb_python_packages[ansible_distribution_major_version] }}"
    download_dir: "{{ mongodb_rpms_download_dir_target_node }}"

- name: Include tasks to install python on version 8
  ansible.builtin.include_tasks:
    file: python-for-8.yaml
  when: ansible_distribution_major_version == "8"

- name: Include tasks to install python on version 9
  ansible.builtin.include_tasks:
    file: python-for-9.yaml
  when: ansible_distribution_major_version == "9"

- name: Download Python wheels
  ansible.builtin.import_role:
    name: offline
    tasks_from: download-wheels
  vars:
    with_deps: true
    wheel_files: "{{ mongodb_python_dependencies[ansible_distribution_major_version] }}"
    download_dir: "{{ mongodb_wheels_download_dir_target_node }}"

- name: Uninstall Python rpms
  ansible.builtin.yum:
    name: "{{ item }}"
    state: absent
    autoremove: true
  with_items: "{{ python_install_result.results | selectattr('changed', 'equalto', true) | map(attribute='item') }}"
