# Copyright (c) 2022, Itential, LLC
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)---

- name: Install Python packages (online)
  ansible.builtin.yum:
    name: "{{ item }}"
    state: present
  with_items: "{{ mongodb_python_packages[ansible_distribution_major_version] }}"
  register: python_install_result
  when: not offline_install

- name: Create Python symlinks
  ansible.builtin.import_role:
    name: common
    tasks_from: create-python3-symlinks
