# Copyright (c) 2022, Itential, LLC
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)

# Default feature flags
# Enable everything by default, override in the hosts file if required
iag_enable_ansible: true
iag_enable_terraform: true
iag_enable_nornir: true
iag_enable_netmiko: true
iag_enable_scripts: true
iag_enable_netconf: true
iag_enable_httpreq: true
iag_haproxy: false

# Location of IAG assets
iag_install_dir: /opt/automation-gateway

# Location of IAG data
iag_data_dir: /opt/automation-gateway

# Location of IAG logs
iag_log_dir: /var/log/automation-gateway

# Default port
iag_port: 8083

# location of IAG config file
iag_properties_location: /etc/automation-gateway

iag_user: itential
iag_group: itential

# These are only used for RHEL7 installs and are not referenced by RHEL8/9 tasks
iag_openssl_url: https://www.openssl.org/source/openssl-1.0.2q.tar.gz
iag_python_src_url: https://www.python.org/ftp/python/3.9.5/Python-3.9.5.tgz
iag_python_version: 3.9.5

# Default HTTPS/SSL settings
iag_https: false
iag_https_port: 8443
iag_ssl_copy_certs: true
iag_ssl_dir: "{{ iag_install_dir }}/conf/certs"
iag_ssl_cert_src: server.crt
iag_ssl_cert_dest: "{{ iag_ssl_dir }}/{{ iag_ssl_cert_src }}"
iag_ssl_key_src: server.key
iag_ssl_key_dest: "{{ iag_ssl_dir }}/{{ iag_ssl_key_src }}"
iag_ssl_rootca_src: rootCA.crt
iag_ssl_rootca_dest: "{{ iag_ssl_dir }}/{{ iag_ssl_rootca_src }}"
iag_tlsv1_2: false
