# Copyright (c) 2022, Itential, LLC
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)

gateway_packages:
  - "@Development tools"
  - bzip2-devel
  - haproxy
  - libffi-devel
  - libselinux-python
  - libyaml
  - make
  - openldap
  - openldap-clients
  - openssl-devel
  - sqlite-devel
  - unzip
  - wget
  - yaml-cpp
  - yaml-cpp-devel
  - zlib-devel

iag_python_version: 3.9.5
iag_python_src_url: https://www.python.org/ftp/python/3.9.5/Python-3.9.5.tgz

iag_python_dependencies:
  - wheel
  - setuptools==58.0.1

iag_ansible_version: ansible==2.10.0

iag_openssl_url: https://www.openssl.org/source/openssl-1.0.2q.tar.gz

iag_terraform_url: https://releases.hashicorp.com/terraform/0.12.31/terraform_0.12.31_linux_amd64.zip
