# Copyright (c) 2022, Itential, LLC
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)
---
gateway_packages:
  - make
  - gcc-c++

gateway_python_packages:
  - python3
  - python3-pip
  - python3-devel

iag_python_dependencies:
  - ansible-pylibssh
  - flask-ldap3-login==0.9.18
  - grpcio==1.53.0
  - hvac==1.0.2
  - ldap3==2.9.1
  - ncclient==0.6.10
  - netmiko==4.1.2
  - nornir==3.3.0
  - nornir-netmiko==0.2.0
  - nornir-utils==0.2.0
  - pygnmi==0.8.9
  - setuptools==58.0.1
  - wheel

iag_ansible_version: ansible==7.7.0

iag_terraform_url: https://releases.hashicorp.com/terraform/0.12.31/terraform_0.12.31_linux_amd64.zip