# Copyright (c) 2022, Itential, LLC
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)

- name: Upload the IAP bin file using rsync
  ansible.posix.synchronize:
    src: "{{ iap_bin_file }}"
    dest: "{{ iap_install_dir }}/{{ iap_bin_file }}"
    rsync_opts:
      - "--copy-links"
  when: upload_using_rsync

- name: Upload the IAP bin file using copy
  ansible.builtin.copy:
    src: "{{ iap_bin_file }}"
    dest: "{{ iap_install_dir }}/{{ iap_bin_file }}"
    mode: "0775"
    force: false
  when: not upload_using_rsync

- name: Change bin file ownership, group and permissions
  ansible.builtin.file:
    path: "{{ iap_install_dir }}/{{ iap_bin_file }}"
    owner: "{{ iap_user }}"
    group: "{{ iap_group }}"
    mode: "0755"

# Extract bin file contents
# -e Extract tar archive and exit
# -y Assume defaults for all prompts & run non-interactively
# -d Installation directory, where to extract the files
# We are no longer going to depend on the shell code that is contained within
# the bin file. Just extract the tar from the bin and perform the rest of the
# upgrade with this role for transparency. If the extracted directory already
# exists then do nothing (creates).
- name: Extract the bin file contents
  ansible.builtin.command:
    cmd: "{{ iap_install_dir }}/{{ iap_bin_file }} -ey -d {{ iap_install_dir }}"
    chdir: "{{ iap_install_dir }}"
    creates: "{{ iap_install_dir }}/{{ iap_package_name }}"

- name: Create the "current" symlink
  ansible.builtin.file:
    path: "{{ iap_install_dir }}/current"
    src: "{{ iap_install_dir }}/{{ iap_package_name }}"
    owner: "{{ iap_user }}"
    group: "{{ iap_group }}"
    state: link
    mode: "0755"

- name: Create systemd file
  ansible.builtin.template:
    src: automation-platform.service.j2
    dest: /usr/lib/systemd/system/automation-platform.service
    mode: "0644"

- name: Remove Itential source file
  when: remove_iap_source_file | bool
  ansible.builtin.file:
    path: "{{ iap_install_dir }}/{{ iap_bin_file }}"
    state: absent

- name: Write IAP release file
  ansible.builtin.lineinfile:
    path: "{{ itential_release_file }}"
    line: "PLATFORM={{ iap_release }}"
    mode: "0644"
    create: true
