# Copyright (c) 2024, Itential, Inc
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)
---
# The RabbitMQ home directory
rabbitmq_home_dir: "{{ rabbitmq_default_home_dir }}"

# The RabbitMQ port
rabbitmq_port: "{{ rabbitmq_default_port }}"

# The RabbitMQ management console port
rabbitmq_mgt_console_port: "{{ rabbitmq_default_mgt_console_port }}"

# The default RabbitMQ user and group
rabbitmq_owner: rabbitmq
rabbitmq_group: rabbitmq

# Flag to enable/disable IPv6
rabbitmq_bind_ipv6: true

# The hostnames and/or IP address on which RabbitMQ should listen for
# client connections.
rabbitmq_bind_addr: 127.0.0.1

# Log settings
rabbitmq_log_dir: /var/log/rabbitmq
rabbitmq_log_file: rabbit.log
rabbitmq_log_file_level: info

# Inter-node connections use a buffer for data pending to be sent. Temporary throttling on
# inter-node traffic is applied when the buffer is at max allowed capacity. The limit is
# controlled via the RABBITMQ_DISTRIBUTION_BUFFER_SIZE environment variable in kilobytes.
# Default value is 128 MB (128000 kB).
#
# In clusters with heavy inter-node traffic increasing this value may have a positive effect
# on throughput. Values lower than 64 MB are not recommended.
# rabbitmq_distribution_buffer_size: 128000

# The largest allowed message payload size in bytes. Messages of larger size will be
# rejected with a suitable channel exception. Default: 134217728, Max value: 536870912
# rabbit_max_msg_size: 536870911

# Makes it possible to override the total amount of memory available, as opposed to
# inferring it from the environment using OS-specific means. This should only be used
# when actual maximum amount of RAM available to the node doesn't match the value
# that will be inferred by the node, e.g. due to containerization or similar
# constraints the node cannot be aware of. The value may be set to an integer number
# of bytes or, alternatively, in information units (e.g `8GB`). For example, when the
# value is set to 4 GB, the node will believe it is running on a machine with 4 GB of RAM.
# Default: undefined (not set or used).
# rabbit_total_mem_available_override: 8GB

# Offline install settings
# Refer to the offline variables in common_vars for additional settings
packages_path: "{{ itential_packages_path }}/{{ iap_release }}/rabbitmq"
