# Copyright (c) 2022, Itential, LLC
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)

# The Location of the config rabbitmq config file
rabbitmq_config: /etc/rabbitmq/rabbitmq.conf

# The default rabbitmq port
rabbitmq_port: 5672

# The default rabbitmq mgt console port
rabbitmq_mgt_console_port: 15672

# The default rabbitmq user and group
rabbitmq_owner: rabbitmq
rabbitmq_group: rabbitmq

# Flag to enable/disable IPv6
rabbitmq_bind_ipv6: true

# The hostnames and/or IP address on which rabbitmq should listen for
# client connections.
rabbitmq_bind_addr: 127.0.0.1

rabbitmq_user: itential
rabbitmq_password: itential
rabbitmq_admin_user: admin
rabbitmq_admin_password: admin

# The largest allowed message payload size in bytes. Messages of larger size will be
# rejected with a suitable channel exception. Default: 134217728, Max value: 536870912
#rabbit_max_msg_size: 536870911

# Makes it possible to override the total amount of memory available, as opposed to
# inferring it from the environment using OS-specific means. This should only be used
# when actual maximum amount of RAM available to the node doesn't match the value
# that will be inferred by the node, e.g. due to containerization or similar
# constraints the node cannot be aware of. The value may be set to an integer number
# of bytes or, alternatively, in information units (e.g `8GB`). For example, when the
# value is set to 4 GB, the node will believe it is running on a machine with 4 GB of RAM.
# Default: undefined (not set or used).
#rabbit_total_mem_available_override: 8GB
