# Copyright (c) 2022, Itential, LLC
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)

- name: Disable safe repository checks
  ansible.builtin.command:
    cmd: "git config --global --add safe.directory '*'"
  when: disable_git_safe_repo_checks
  changed_when: true

- name: Install rpms required for download
  ansible.builtin.yum:
    name: "{{ item }}"
    state: present
  with_items:
    - git
    - jq
  register: install_result

- name: Install NodeJS
  ansible.builtin.include_tasks:
    file: install-nodejs.yml

- name: Download and fetch opensource adapters
  when:
    - itential_adapters is defined
    - itential_adapters is iterable
    - itential_adapters | length > 0
  block:
    - name: Download opensource adapters
      ansible.builtin.import_role:
        name: offline
        tasks_from: download-adapters
      vars:
        adapters: "{{ itential_adapters }}"
        download_dir: "{{ iap_adapters_download_dir_target_node }}/opensource"

    - name: Find all downloaded opensource adapters
      ansible.builtin.find:
        paths: "{{ iap_adapters_download_dir_target_node }}/opensource"
        patterns: "*.tgz"
      register: opensource_adapters

    - name: Copy opensource adapters to control node
      ansible.builtin.fetch:
        src: "{{ item.path }}"
        dest: "{{ iap_adapters_download_dir_control_node }}/opensource/"
        flat: true
      with_items: "{{ opensource_adapters.files }}"

- name: Download and fetch opensource adapters
  when:
    - custom_adapters is defined
    - custom_adapters is iterable
    - custom_adapters | length > 0
  block:
    - name: Download custom adapters
      ansible.builtin.import_role:
        name: offline
        tasks_from: download-adapters
      vars:
        adapters: "{{ custom_adapters }}"
        download_dir: "{{ iap_adapters_download_dir_target_node }}/custom"

    - name: Find all downloaded custom adapters
      ansible.builtin.find:
        paths: "{{ iap_adapters_download_dir_target_node }}/custom"
        patterns: "*.tgz"
      register: custom_adapters

    - name: Copy custom adapters to control node
      ansible.builtin.fetch:
        src: "{{ item.path }}"
        dest: "{{ iap_adapters_download_dir_control_node }}/custom/"
        flat: true
      with_items: "{{ custom_adapters.files }}"

- name: Uninstall rpms required for download
  ansible.builtin.yum:
    name: "{{ item }}"
    state: absent
    autoremove: true
  with_items: "{{ install_result.results | selectattr('changed', 'equalto', true) | map(attribute='item') }}"

- name: Uninstall nodejs rpms
  ansible.builtin.yum:
    name: "{{ item }}"
    state: absent
    autoremove: true
  with_items: "{{ nodejs_install_result.results | selectattr('changed', 'equalto', true) | map(attribute='item') }}"
