# Copyright (c) 2022, Itential, LLC
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)

- name: Validate wheels_path is set
  ansible.builtin.fail:
    msg: "wheels_path is not set"
  when: not wheels_path

- name: Create temporary working directory
  ansible.builtin.tempfile:
    state: directory
  register: install_wheels_temp_dir

- name: Copy wheel files to target node
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ install_wheels_temp_dir.path }}/{{ item | basename }}"
    mode: '0644'
  with_fileglob:
    - "{{ wheels_path }}/*.whl"
    - "{{ wheels_path }}/*.tar.gz"

- name: Find Pip wheel file on target node
  ansible.builtin.find:
    paths: "{{ install_wheels_temp_dir.path }}"
    patterns:
      - "pip*.whl"
  register: pip_wheel_list

- name: Install Pip wheel file
  ansible.builtin.pip:
    name: "{{ pip_wheel_list.files | map(attribute='path') | list | sort }}"
    executable: "{{ virtual_env is defined | ternary(omit, 'pip3') }}"
    virtualenv: "{{ virtual_env is defined | ternary(virtual_env, omit) }}"
    extra_args: --no-index
  when: pip_wheel_list.files | length > 0

- name: Find Wheel wheel file on target node
  ansible.builtin.find:
    paths: "{{ install_wheels_temp_dir.path }}"
    patterns:
      - "wheel*.whl"
  register: wheel_wheel_list

- name: Install Wheel wheel file
  ansible.builtin.pip:
    name: "{{ wheel_wheel_list.files | map(attribute='path') | list | sort }}"
    executable: "{{ virtual_env is defined | ternary(omit, 'pip3') }}"
    virtualenv: "{{ virtual_env is defined | ternary(virtual_env, omit) }}"
    extra_args: --no-index
  when: wheel_wheel_list.files | length > 0

- name: Find wheel files on target node
  ansible.builtin.find:
    paths: "{{ install_wheels_temp_dir.path }}"
    patterns:
      - "*.whl"
      - "*.tar.gz"
    excludes:
      - "pip*.whl"
      - "wheel*.whl"
  register: wheel_list

- name: Install wheel files
  ansible.builtin.pip:
    name: "{{ wheel_list.files | map(attribute='path') | list | sort }}"
    executable: "{{ virtual_env is defined | ternary(omit, 'pip3') }}"
    virtualenv: "{{ virtual_env is defined | ternary(virtual_env, omit) }}"
    extra_args: --no-index --no-build-isolation

- name: Remove temporary working directory
  ansible.builtin.file:
    path: "{{ install_wheels_temp_dir.path }}"
    state: absent
