# Copyright (c) 2022, Itential, LLC
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)

# Disclaimer
# This playbook is not officially supported by Itential at this time.  Use at your own risk.

### IAP
- name: Patch IAP
  hosts: platform
  become: true
  roles:
    - role: itential.deployer.common_vars
  tasks:
    - name: Patch IAP
      ansible.builtin.import_role:
        name: itential.deployer.platform
        tasks_from: upgrade-iap
