# Copyright (c) 2024, Itential, Inc
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)
---
# The RabbitMQ YUM repo base URLs
rabbitmq_server_repo_baseurl: "https://packagecloud.io/rabbitmq/rabbitmq-server/el/$releasever/$basearch"
rabbitmq_erlang_repo_baseurl: "https://packagecloud.io/rabbitmq/erlang/el/$releasever/$basearch"

# The Location of the RabbitMQ config file
rabbitmq_config: /etc/rabbitmq/rabbitmq.conf

# The location of the RabbitMQ environment file
rabbitmq_env_config: /etc/rabbitmq/rabbitmq-env.conf

# The RabbitMQ directory defaults
rabbitmq_default_home_dir: /var/lib/rabbitmq
rabbitmq_default_log_dir: /var/log/rabbitmq

# The RabbitMQ port defaults
rabbitmq_default_port: 5672
rabbitmq_default_mgt_console_port: 15672
rabbitmq_default_distribution_buffer_size: 128000
